"""empty message

Revision ID: c680f182965e
Revises: 
Create Date: 2022-11-10 11:00:35.787975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c680f182965e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City',
    sa.Column('idcity', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('country', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('idcity')
    )
    op.create_table('Hotel',
    sa.Column('idhotel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('idhotel')
    )
    op.create_table('Payment',
    sa.Column('idpayment', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('idpayment')
    )
    op.create_table('Transport',
    sa.Column('idtransport', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('idtransport')
    )
    op.create_table('User',
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('surname', sa.String(length=15), nullable=True),
    sa.Column('passport', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('iduser')
    )
    op.create_table('HotelsChoice',
    sa.Column('idchoice', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.idcity'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['Hotel.idhotel'], ),
    sa.PrimaryKeyConstraint('idchoice')
    )
    op.create_table('Trip',
    sa.Column('idtrip', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transport_id'], ['Transport.idtransport'], ),
    sa.PrimaryKeyConstraint('idtrip')
    )
    op.create_table('Booking',
    sa.Column('idbooking', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['User.iduser'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['Payment.idpayment'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['Trip.idtrip'], ),
    sa.PrimaryKeyConstraint('idbooking')
    )
    op.create_table('Stop',
    sa.Column('idstop', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.idcity'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['Trip.idtrip'], ),
    sa.PrimaryKeyConstraint('idstop')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stop')
    op.drop_table('Booking')
    op.drop_table('Trip')
    op.drop_table('HotelsChoice')
    op.drop_table('User')
    op.drop_table('Transport')
    op.drop_table('Payment')
    op.drop_table('Hotel')
    op.drop_table('City')
    # ### end Alembic commands ###
